service: myseverlessproject
app: myserverlessproject1
org: personlink

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: default

plugins: 
  - serverless-s3-sync
  - serverless-webpack

package: 
  individually: true

custom:
  tableName: playper-tables
  s3Sync: 
    - bucketName: yuuki-aws-dev.work
      localDir: UploadData

functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

resources: 
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: yuuki-aws-dev.work
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST